# Generated by Django 3.0.4 on 2020-03-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200323_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='nickName',
        ),
    ]
